## Linear Algebra Part III

In this final article of the three part series, we will talk about two types of decomposition, specifically LU and Eigen Decomposition. And then finally talk about how we can use Linear Algebra to solve the Linear Regression Problem. 

If you havent read the first two articles, they are linked below:
1. Linear Algebra with NumPy- Part I
2. Linear Algebra with NumPy- Part II 

For this final article, we will combine NumPy and SciPy to perform some decompositions. 

### Part I: Introduction 
Before jumping into the two decomposition, lets talk a little bit about what matrix decompositions are and why they are helpful. 

A matrix decomposition or matrix factorization is essentially reducing your matrix to a product of matrices. The decomposition is done because it makes performing computations easier on the resulting matrices than the original matrix. 

A common analogy for matrix decomposition is the factoring of numbers, such as the factoring of 10 into 2 x 5. For this reason, matrix decomposition is also called matrix factorization. Like factoring real values, there are many ways to decompose a matrix, hence there are a range of different matrix decomposition techniques, each helping solve a particular class of problems. Some examples include LU decomposition, Eigen decomposition, QR decomposition, & Singular Value decomposition. <sup>1</sup> 


### Part II: LU Decomposition

The first type of decomposition we will look at is the LU decomposition. Here the "L" stands for Lower Triangular Matrix and "U" stands for Upper Triangular Matrix. This means we decompose our original matrix into the product of a lower and upper triangular matrices. This type of decompoisition is particularly useful when solving a linear system of equations; because it is much easier to deal with triangular matrices, it is very desirable to decompose matrices into product of triangular matrices when solving linear equations.

We can write this as: 

$$A = LU$$

where $A$ is a matrix, $L$ is the lower triangular matrix and $U$ is the upper triangular matrix. 

In this article, we will talk about three different ways to decompose a matrix into a lower and upper triangular matrices, and they differ in the way they set up the Lower or Upper triangular matrix:
1. Doolittle ($diag(L) = 1$)
2. Crout ($diag(U) = 1$)
3. Cholesky ($diag(U) = diag(L)$)

We will dive into each one and show how different set ups give us the same result. 

1. <b> Doolittle </b>

In this method of LU decomposition, the Lower Matrix is set up as:

$L_{3x3} = \begin{pmatrix} 
        1 & 0 & 0  \\
        x & 1 & 0  \\
        x & x & 1 \\
     \end{pmatrix}$

where x is any number. 

Let A be a 3x3 matrix 

$A = \begin{pmatrix} 
        1 & 2 & 4  \\
        3 & 8 & 14 \\
        2 & 6 & 13  
     \end{pmatrix}$

We can set the $L$ and $U$ matrix as:

$L = \begin{pmatrix} 
        1 & 0 & 0  \\
        L_{2,1} & 1 & 0 \\
        L_{3,1} & L_{3,2} & 1  
     \end{pmatrix}$

$U = \begin{pmatrix} 
        U_{1,1} & U_{1,2} & U_{1,3}  \\
        0 & U_{2,2} & U_{2,3} \\
        0 & 0 & U_{3,3}  
     \end{pmatrix}$

We can caluculate the product LU as:

$LU = \begin{pmatrix} 
        U_{1,1} & U_{1,2} & U_{1,3}  \\
        L_{2,1}U_{1,1} & L_{2,1}U_{1,2} + U_{2,2} & L_{2,1}U_{1,3} + U_{2,3} \\
        L_{3,1}U_{1,1} & L_{3,1}U_{1,2} + L_{3,2}U_{2,2} & L_{3,1}U_{1,3} + L_{3,2}U_{2,3} + U_{3,3}  
     \end{pmatrix}=
     \begin{pmatrix}
        1 & 2 & 4  \\
        3 & 8 & 14 \\
        2 & 6 & 13  
     \end{pmatrix}$

Once you solve the above equation we get the following values:

$L = \begin{pmatrix} 
        1 & 0 & 0  \\
        3 & 1 & 0 \\
        2 & 1 & 1  
     \end{pmatrix}$
$U = \begin{pmatrix} 
        1 & 2 & 4  \\
        0 & 2 & 2 \\
        0 & 0 & 3  
     \end{pmatrix}$

We can confirm, multiplying these two matrices would give us the original matrix A. 

In [1]:
import numpy as np

In [2]:
l = np.array([[1,0,0],[3,1,0],[2,1,1]])
u = np.array([[1,2,4], [0,2,2],[0,0,3]])

In [3]:
np.matmul(l,u)

array([[ 1,  2,  4],
       [ 3,  8, 14],
       [ 2,  6, 13]])

As you can see, the product produces the same matrix A. 

The second method is <b>Crout</b>. In this method the upper triangular matrix has 1's on its diagonal. 

Taking the same matrix A as an example:

$A = \begin{pmatrix} 
        1 & 2 & 4  \\
        3 & 8 & 14 \\
        2 & 6 & 13  
     \end{pmatrix}$
     
We can set the $L$ and $U$ matrix as:

$L = \begin{pmatrix} 
        L_{1,1} & 0 & 0  \\
        L_{2,1} & L_{2,2} & 0 \\
        L_{3,1} & L_{3,2} & L_{3,3}  
     \end{pmatrix}$

$U = \begin{pmatrix} 
        1 & U_{1,2} & U_{1,3}  \\
        0 & 1 & U_{2,3} \\
        0 & 0 & 1  
     \end{pmatrix}$
     
The product of the two matrices would be:

$LU = \begin{pmatrix} 
        L_{1,1} & L_{1,1}U_{1,2} & L_{1,1}U_{1,3}  \\
        L_{2,1} & L_{2,1}U_{1,2} + L_{2,2} & L_{2,1}U_{1,3} + L_{2,2}U_{2,3} \\
        L_{3,1} & L_{3,1}U_{1,2} + L_{3,2} & L_{3,1}U_{1,3} + L_{3,2}U_{2,3} + L_{3,3}  
     \end{pmatrix}=
     \begin{pmatrix}
        1 & 2 & 4  \\
        3 & 8 & 14 \\
        2 & 6 & 13  
     \end{pmatrix}$
     
Once you solve the above equation we get the following values:

$L = \begin{pmatrix} 
        1 & 0 & 0  \\
        3 & 2 & 0 \\
        2 & 2 & 3  
     \end{pmatrix}$
$U = \begin{pmatrix} 
        1 & 2 & 4  \\
        0 & 1 & 1 \\
        0 & 0 & 1  
     \end{pmatrix}$
     
We can confirm the product of these two matrices would give us the original matrix A.

In [4]:
l = np.array([[1,0,0],[3,2,0],[2,2,3]])
u = np.array([[1,2,4], [0,1,1],[0,0,1]])

In [5]:
np.matmul(l,u)

array([[ 1,  2,  4],
       [ 3,  8, 14],
       [ 2,  6, 13]])

Finally, the last method is <b>Cholesky</b> method where both the diagonals of the upper and lower triangular matrix are the same. 

We will follow the same example as above and decompose the matrix $A$ into the two matrices. 

In this case

$L = \begin{pmatrix} 
        x_{1,1} & 0 & 0  \\
        L_{2,1} & x_{2,2} & 0 \\
        L_{3,1} & L_{3,2} & x_{3,3}  
     \end{pmatrix}$

$U = \begin{pmatrix} 
        x_{1,1} & U_{1,2} & U_{1,3}  \\
        0 & x_{2,2} & U_{2,3} \\
        0 & 0 & x_{3,3} 
     \end{pmatrix}$

Which gives us:

$LU = \begin{pmatrix} 
        x_{1,1}^{2} & x_{1,1}U_{1,2} & x_{1,1}U_{1,3}  \\
        x_{1,1}L_{2,1} & L_{2,1}U_{1,2} + x_{2,2}^{2} & L_{2,1}U_{1,3} + x_{2,2}U_{2,3} \\
        x_{1,1}L_{3,1} & L_{3,1}U_{1,2} + x_{2,2}L_{3,2} & L_{3,1}U_{1,3} + L_{3,2}U_{2,3} + x_{3,3}^{2}  
     \end{pmatrix}=
     \begin{pmatrix}
        1 & 2 & 4  \\
        3 & 8 & 14 \\
        2 & 6 & 13  
     \end{pmatrix}$
     
Solving this system of equation gives us these two matrices:

$L = \begin{pmatrix} 
        1 & 0 & 0  \\
        3 & \sqrt{2} & 0 \\
        2 & 2/\sqrt{2} & \sqrt{3}  
     \end{pmatrix}$
$U = \begin{pmatrix} 
        1 & 2 & 4  \\
        0 & \sqrt{2} & 2/\sqrt{2} \\
        0 & 0 & \sqrt{3}  
     \end{pmatrix}$
     
We can confirm the product of these two matrices would give us the original matrix A.

In [6]:
l = np.array([[1,0,0],[3,np.sqrt(2),0],[2,2/np.sqrt(2),np.sqrt(3)]])
u = np.array([[1,2,4], [0,np.sqrt(2),2/np.sqrt(2)],[0,0,np.sqrt(3)]])

In [7]:
np.matmul(l,u)

array([[ 1.,  2.,  4.],
       [ 3.,  8., 14.],
       [ 2.,  6., 13.]])

Now instead of calculating the L and U matrices by hand, the `scipy` package provides the `linalg.lu` function that gives you the LU decomposition of a matrix. Note that this functions uses a slightly different method to calculate the LU Decomposition. The `linalg.lu` function uses what is called a PLU decomposition.

More information about the scipy function can be found [here](https://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.lu.html).

And more information about how the PLU decomposition works can be found [here](https://johnfoster.pge.utexas.edu/numerical-methods-book/LinearAlgebra_LU.html).

In [8]:
import scipy 
import scipy.linalg

a = np.array([[1,2,4],[3,8,14],[2,6,13]])

p,l,u = scipy.linalg.lu(a)

print("Lower Matrix")
print(l)

print("\n")

print("Upper Matrix")
print(u)

Lower Matrix
[[ 1.          0.          0.        ]
 [ 0.66666667  1.          0.        ]
 [ 0.33333333 -1.          1.        ]]


Upper Matrix
[[ 3.          8.         14.        ]
 [ 0.          0.66666667  3.66666667]
 [ 0.          0.          3.        ]]


Reason why the LU Decomposition is so important is that it gives us an alternate approach to solving linear systems. We know that Gaussian Elimination can be used to solve a linear system of the form $Ax = b$ (more information on Gaussian elimination in my first article). However, the algorithm for using Guassian Elimination takes $O(\frac{1}{3}n^{3})$ opertations. This is where LU Decomposition can help. 

Let say we have the linear system $Ax = b$, where the matrix $A$ can be decomposed into a lower and upper triangular matrix. What we get is:

$LUx = b$ 
Let $y = Ux$ 

We can solve the equation $Ly = b$ using forward substituion in $O(n^{2})$ operations. And then we can solve $Ux = y$ using back substitution in another $O(n^{2})$ steps. 

This reduces the time complexity to $O(2n^{2})$ steps. For large systems this can reduce the time significantly. $^{2,3}$

## Part III: Eigen Decomposition

The next decomposition is the Eigen Decomposition. To find the eigenvector and eigenvalue of a matrix A, we know there exists a non-zero vector $u \in \mathcal{C}^{n}$ for which a scalar $\lambda$ satisfies the following equations:

$Au = \lambda u$


We can put the eigenvectors of the matrix A into a matrix denoted by U, where each column represents an eigenvector of the matrix A. The eigenvalues are stored as a diagonal matrix denoted by $\Lambda$. 
We can rewrite the above equation as: 

$AU = \Lambda U$

Solving for A, we get the equation: $A = U \Lambda U^{-1}$

This gives us the eigendecomposition of the matrix A. 

**Note not all matrices have eigenvalues

Lets solve an example to see how it works:

We have a matrix A

$\begin{pmatrix} 
        1 & -2 \\
        3 & -4 
     \end{pmatrix}$
     
From my previous article, we know we can get the eigenvalues and eigenvectors of a 2x2 matrix by solving the characteristic equation 

$ det(A - \lambda I) = 0$

which, for a 2x2 matrix is equal to:

$ \lambda^{2} - \lambda Tr(A) + det(A) = 0$

Solving the above equation, we get the following eigenvalues:

$\lambda = -1$ & $\lambda = -2$

The eigenvectors for these corresponding eigenvalues are:

For $\lambda = -1$ 

t$\begin{pmatrix} 
  1 \\ 1
  \end{pmatrix}
$
  
where t is a nonzero scalar 

For $\lambda = -2$ 

t$\begin{pmatrix} 
  2 \\ 3
  \end{pmatrix}
$
  
where t is a nonzero scalar 

So using the notations introduced above our U matrix would be 

$ \begin{pmatrix} 
        1 & 2 \\
        1 & 3
  \end{pmatrix}$ 
  
and $\Lambda$ equals 

$ \begin{pmatrix} 
        -1 & 0 \\
        0 & -2
  \end{pmatrix}$
  

We can confirm that the product of these matrices would give us our original matrix A 

In [9]:
from numpy.linalg import norm
U = np.array([[1,2],[1,3]])

lam = np.array([[-1,0],[0,-2]])

In [10]:
U

array([[1, 2],
       [1, 3]])

In [11]:
from numpy.linalg import inv
A = U @ lam @ inv(U)

A

array([[ 1., -2.],
       [ 3., -4.]])

As you can see, this gives us the original matrix A back. 

We can use the `eig` function from numpy to find the eigenvalues and eigenvectors along with `inv` function to confirm as well

In [12]:
from numpy import linalg as lg
Eigenvalues, Eigenvectors = lg.eig(np.array([

[1, -2],

[3, -4]


]))

Lambda = np.diag(Eigenvalues)


Eigenvectors @ Lambda @ lg.inv(Eigenvectors)

array([[ 1., -2.],
       [ 3., -4.]])

Eigendecompostion plays an important role in many machine learning applications. Some machine learning applications include Principal Component Analysis, Spectral Clustering, Computer Vision and many more.<sup>4</sup>

<sup>1</sup> https://machinelearningmastery.com/introduction-to-matrix-decompositions-for-machine-learning/

<sup>2</sup> https://johnfoster.pge.utexas.edu/numerical-methods-book/LinearAlgebra_LU.html

<sup>3</sup> https://www.sciencedirect.com/topics/computer-science/gaussian-elimination

<sup>4</sup> https://towardsdatascience.com/the-essence-of-eigenvalues-and-eigenvectors-in-machine-learning-f28c4727f56f